var app = angular.module('modone', []);

app.controller('AppController', ['$scope','$http' , function($scope,$http) {
    //Variables iniciales
    
   
    $scope.mostrarSeleccionUsuario = true; 
    $scope.mostrarServiciosEstudiante = false;
    $scope.mostrarServiciosOrganizacion= false;
    $scope.mostrarServiciosCoordinador= false;
    $scope.mostrarBecasDisponiblesEstudiante= false;
    $scope.mostrarBecasDisponiblesCoordinador= false;
    $scope.mostrarRegistrarBecaCoordinador= false;
    $scope.mostrarBecaEstudiante= false;
    $scope.mostrarBecaCoordinador= false;
    $scope.mostrarOpinionesEstudiante= false;
    $scope.mostrarRegistrarOpinionEstudiante= false;
    $scope.mostrarProyectosEstudiantes= false;
    $scope.mostrarProyectosOrganizacion= false;
    $scope.mostrarProyectosOrganizacionEstudiantes= false;
    $scope.mostrarProyectoOrganizacion= false;
    $scope.mostrarProyectoEstudiantes= false;
    $scope.mostrarRegistrarProyectoOrganizacion= false;
    
    console.info($scope.mostrarSeleccionUsuario);
    $scope.irASeleccionUsuario = function(){
        $scope.mostrarSeleccionUsuario = true;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAServiciosEstudiante = function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = true;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAServiciosOrganizacion = function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= true;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAServiciosCoordinador = function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= true;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irABecasDisponiblesEstudiante = function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= true;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
        $http.get('rest/becasECI').
                success(function (data, status, headers, config) {
                    $scope.becas=data;
                }).
                error(function (data, status, headers, config) {
                });
    }
    $scope.irABecasDisponiblesCoordinador= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= true;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irARegistrarBecaCoordinador= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= true;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irABecaEstudiante= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= true;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irABecaCoordinador= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= true;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAOpinionesEstudiante= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= true;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irARegistrarOpinionEstudiante= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= true;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAProyectosEstudiantes= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= true;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAProyectosOrganizacion= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= true;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAProyectosOrganizacionEstudiantes= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= true;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAProyectoOrganizacion= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= true;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irAProyectoEstudiantes= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= true;
        $scope.mostrarRegistrarProyectoOrganizacion= false;
    }
    $scope.irARegistrarProyectoOrganizacion= function(){
        $scope.mostrarSeleccionUsuario = false;
        $scope.mostrarServiciosEstudiante = false;
        $scope.mostrarServiciosOrganizacion= false;
        $scope.mostrarServiciosCoordinador= false;
        $scope.mostrarBecasDisponiblesEstudiante= false;
        $scope.mostrarBecasDisponiblesCoordinador= false;
        $scope.mostrarRegistrarBecaCoordinador= false;
        $scope.mostrarBecaEstudiante= false;
        $scope.mostrarBecaCoordinador= false;
        $scope.mostrarOpinionesEstudiante= false;
        $scope.mostrarRegistrarOpinionEstudiante= false;
        $scope.mostrarProyectosEstudiantes= false;
        $scope.mostrarProyectosOrganizacion= false;
        $scope.mostrarProyectosOrganizacionEstudiantes= false;
        $scope.mostrarProyectoOrganizacion= false;
        $scope.mostrarProyectoEstudiantes= false;
        $scope.mostrarRegistrarProyectoOrganizacion= true;
        
            
    }
}]);